name: CI-CD IIS Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Restore NuGet Packages
      run: dotnet restore

    - name: Build Project
      run: dotnet build -c Release

    - name: Publish Project
      run: dotnet publish -c Release -o publish

    - name: Stop IIS
      run: iisreset /stop

    - name: Deploy Files
      run: xcopy /E /Y /I .\publish C:\inetpub\wwwroot\PaginationApi\

    - name: Start IIS
      run: iisreset /start
